[package]
name = "statusmith"
version = "0.1.0"
edition = "2021"
description = "Tray app for crafting custom Discord Rich Presence statuses"
license = "MIT"
repository = "https://github.com/Londopy/statusmith"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-autostart = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-updater = "2"
rfd = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = 2
strip = true
